name: Show Pull Request Event

on:
  pull_request:
    branches:
      - main

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: steps name
        run: echo ${{ github.event.head_commit.message }}

