name: Show Pull Request Event

on:
  pull_request:
    branches:
      - main

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: steps name
        run: echo $(git show -s --format=%s)
