name: Show Pull Request Event

on:
  pull_request:
    branches:
      - main

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: steps name
        run: echo ${{ github.event.commits[0].message }}
